  #define endereco  0x27
  #define colunas   16
  #define linhas    2
  #define ledRed    10  
  #define ledGreen  9 
  #define ledBlue   8  
  #define botao1P   7
  #define botao2P   6
  #define botao1M   5
  #define botao2M   4
  #define botaoR    3
  #define buzzer    2